.github/workflows/test.yaml

Previously we relied on the fact that `pre-commit-action` runs `docker-cache` to test `docker-cache`. Since `pre-commit-action` pins the version of `docker-cache` to ensure its own stability, this created unnecessary friction to testing changes to `docker-cache` before they were released. Now that `pre-commit-action` has been released as an action, call it in a workflow that also self-tests `docker-cache` rather than reuse its entire workflow.

ci(test): Self-test action on current branch

---

pyproject.toml

The name pre-commit-action was erroneously used in place of docker-cache.

docs(pyproject): Correct name

---

.tool-versions

The Yarn plugin for asdf only supports Yarn 1.x, because Yarn 2+ doesn't support global installation. Hence, manage the version of Yarn 1.x in `.tool-versions`, which is only used to bootstrap Yarn 2+. Continue managing the version of Yarn 2+ in `.yarnrc.yml`.

chore(Yarn): Pin Yarn 1.x version via asdf

---

README.md

Style file paths as code for consistency with our contributing guide and to emphasize that they are to be interpreted verbatim.

docs(README): Format file paths as code

---

.github/workflows/test.yaml

In the Test workflow, the pre-commit-action now runs the Commitizen action, which relies on Git tags. The official GitHub checkout action does a sparse checkout by default, which does not include tags, causing version bumps to fail. Pass `fetch-depth: 0` to instruct the checkout action to perform a full checkout, including tags.

ci(workflow): Check out full repository history

---

.pre-commit-config.yaml

Upgrade all pre-commit hooks to latest.
ScribeMD/pre-commit-hooks 0.4.0 --> 0.5.0

chore(MegaLinter): Upgrade from v5.12.0 to v5.13.0

---

package.json

The `engines.node` field of `package.json` incorrectly listed Node.js at version 16.4.2. We previously used Node.js 16.14.2 but have since upgraded to 16.15.0. asdf manages the Node.js version in use.

chore(Node.js): Correct engine version

---

.tool-versions
.yarnrc.yml

Remind maintainers to keep the Node.js and Yarn versions in use in sync with the `engines` field of `package.json`.

docs(tool-versions): Keep engine versions in sync

---

.gitignore
tsconfig.json

ncc outputs to `dist`, and GitHub Actions requires that its output be tracked. The output of the TypeScript compiler, tsc, should not be tracked as it is only for testing/debugging purposes. Configure tsc to output to a separate `build` directory, and instruct Git to ignore it.

test(tsconfig): Output to build rather than dist

---

tsconfig.json

By default, tsc outputs files with Windows line endings on Windows and Unix line endings on Unix systems. Since nearly all Windows tools support Unix line endings, the rest of our files are configured to use Unix line endings on all platforms for consistency. Configure tsc to do the same.

test(tsconfig): Configure tsc to use line feeds

---

.dictionary.txt
.pre-commit-config.yaml

Remove "vercel" from custom dictionary; it was added to the npm dictionary upstream.
Upgrade all pre-commit hooks to latest versions.
ScribeMD/pre-commit-hooks 0.5.2 --> 0.6.1

chore(MegaLinter): Upgrade from v5.13.0 to v5.14.0

---

.github/workflows/test.yaml
.gitignore
.pre-commit-config.yaml
jest.config.ts
package.json
src/docker.test.ts
src/integration.test.ts
src/main.test.ts
src/post.test.ts
src/util.test.ts
tsconfig.json
yarn.lock

Use experimental support for mocking ESM where necessary. Run tsc before running tests, because Jest swallows any TypeScript errors and hangs, whereas the TypeScript compiler displays helpful error messages. Add GitHub action to publish unit test results to Test workflow.

test(action): Add Jest unit and integration tests

---

.github/workflows/test.yaml

Dependabot runs with read-only permissions by default for security purposes, but EnricoMi/publish-unit-test-result-action requires the `checks:write` scope, and pre-commit-action requires the `contents:write` scope. publish-unit-test-result-action uses the `checks:write` scope to display a summary of its results in a separate workflow in the GitHub Actions UI. pre-commit-action uses the `contents:write` scope to bump the project version via Commitizen. Granting these specific permissions also has the effect of reducing the scope of all unspecified permissions from read to none for pull requests from Dependabot and forks and from write to none for workflows triggered by anything else (even re-runs of Dependabot pull requests). Since this repository is public, most of its data can be read …

ci(GitHub-Actions): Grant minimum necessary scopes

---

src/docker.test.ts

When asserting that mocks were called in the expected order, sort their call orders, which are represented as numbers, numerically. `Array.sort()` sorts alphabetically by default, so pass a comparison function to override this behavior.

test(docker): Sort numerically, not alphabetically

---

src/docker.test.ts

This allows TypeScript to enforce that a number is returned from the comparison function.

style(docker.test): Specify a return type

---

README.md

Virtually all tool homepages link to their GitHub repositories anyways, and the homepages generally offer a more enticing user experience.

docs(README): Link to tool homepages, not repos

---

.markdown-link-check.json
README.md
cspell.config.yaml

Configure markdown-link-check to accept any compression to avoid false positive on GitHub Docs link.

docs(README): Document required permissions

---

jest.config.ts
src/integration.test.ts

Change Jest configuration to `resetMocks` instead of `clearMocks` to eliminate the most substantial mechanism of cross-test interaction.

test(integration): Change Jest to `resetMocks`

---

.github/workflows/test.yaml

Change job name to keep naming convention consistent with other repos.

ci(GitHub-Actions): Improve pre-commit job name

---

src/docker.test.ts

Group duplicated asserts in a helper function.

test(docker): Decompose duplicate asserts

---

.dictionary.txt

Dependabot uses "deps," short for "dependencies," in commit messages, which Commitizen incorporates into the changelog.

ci(dictionary): Add "deps" to custom dictionary

---

src/docker.test.ts

Introduce `assertLoadDockerImages` to call repeated asserts. Add `getInput` argument to `assertCalledInOrder` to test `readOnly` feature.

test(docker): Improve test modularity

---

.pre-commit-config.yaml

When the Poetry dependency Commitizen was upgraded from v2.31.0 to v2.32.2, the pre-commit hook was left at v2.31.0.

chore(pre-commit): Bump commitizen hook to v2.32.2

---

src/integration.test.ts

Add assert that `cache.saveCache` is not called upon cache hit.

test(integration): Assert cache not saved on hit

---

src/integration.test.ts

Assert `child_process.exec` called precisely once in `mockedExec`.

test(integration): Add `child_process.exec` assert

---

src/integration.test.ts

Since `core.error` is called twice in the save on cache miss case, use `nthCalledWith` to check each call rather than `lastCalledWith`, which checks the second call twice. This issue was asymptomatic, because the integration test always calls `core.error` with the same constant string. Reuse `execCallNum` as n for core.error since calls to it are one-to-one with calls to `child_process.exec`.

test(integration): Correct `core.error` assert

---

src/integration.test.ts

Type `command` as a string since it is now used as one. Rename `_command` to `command` since it is no longer an unused argument as the leading underscore incorrectly indicated.

test(integration): Prefer specific type to `any`

---

src/docker.test.ts

Rename `assertCacheHitSave` to `assertSaveCacheHit` for consistency with the analogous helper function in the integration test.

test(docker): Rename a function for consistency

---

README.md

Functionality of docker-cache was changed to filter out images present prior to main step. Document accordingly.

docs(README): Document filtering Docker images

---

package.json
src/docker.test.ts
src/integration.test.ts
src/util.test.ts
yarn.lock

Property-based tests automatically generate a variety of inputs likely to expose bugs. Replace our conventional tests with property-based tests, and stop hard-coding individual test cases except where needed to ensure we maintain 100% test coverage.

test(action): Use fast-check property-based tests

---

.yarnrc.yml

Jest depends on fsevents, which is MacOS-specific. Hence, Yarn doesn't install it on other operating systems by default. This prevents us from running Pivotal Labs' LicenseFinder on this repository, which scans the licenses of the locally installed plugins. Force Yarn to install MacOS-dependencies so they can't break license auditing in the future.

chore(Yarn): Install deps for MacOS and current OS

---

.github/dependabot.yaml

Automatically update Yarn dependencies via Dependabot. Dependabot recently enabled Yarn v2+ support in production behind a feature flag. We have the privilege of being part of the first batch of external repos to receive access! Use the `fix` prefix in commit messages for bumps to production dependencies so Commitizen bumps the patch version. Use the `chore` prefix in commit messages for bumps to development dependencies so that Commitizen doesn't bump the project version.

chore(Dependabot): Add Yarn

---

.github/dependabot.yaml

Dependabot complains: "Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'." Hence, combine the configurations for Yarn production and development dependencies.

chore(Dependabot): Correct Yarn configuration

---

.dictionary.txt
.github/workflows/test.yaml
.gitignore
.pre-commit-config.yaml
.trivyignore
Dockerfile

Replace MegaLinter v5 hooks with v6 hooks.
Suppress false positive on newly-added linter, Checkov. Change `secrets.GITHUB_TOKEN` to `github.token` in `test.yaml` to avoid triggering a false positive from Checkov.
Add `.trivyignore` because newly-added linter Trivy warns: "Specify at least 1 USER command in Dockerfile with non-root user as argument"; see [relevant Trivy documentation](https://avd.aquasec.com/misconfig/dockerfile/general/avd-ds-0002/). We only use the `Dockerfile` for testing, thus we are not concerned with this as a security issue.
Remove "deps" from custom dictionary; it was added to the Python dictionary upstream.
Remove workarounds for rhysd/actionlint#170 as this was fixed upstream.

chore(MegaLinter): Upgrade from v5.16.1 to v6.10.0

---

src/docker.test.ts
src/integration.test.ts
src/main.test.ts
src/post.test.ts
src/util.test.ts

Jest v29 recently shipped with stronger typing. The custom `Mocked` type was never necessary. Replace it with `jest.MockedObject` since we will otherwise encounter errors on upgrade.

test(action): Remove unneeded bespoke `Mocked` type

---

.yarn/sdks/eslint/package.json
.yarn/sdks/prettier/package.json
.yarn/sdks/typescript/package.json

Run `yarn run sdks` to generate the latest SDKs.

chore(Yarn): Update SDKs from 2.6.2 to 2.6.3

---

.dictionary.txt

It is now in the CSpell Python dictionary upstream.

ci(dictionary): Remove setuptools from custom dict

---

.github/workflows/test.yaml

Improve performance of the Test workflow. Yarn dependencies are already installed via the `yarn-install` pre-commit hook.

ci(workflow): Cache Yarn dependencies

---

.yarnrc.yml

This reduces diff noise when running `yarn set version stable`.

chore(yarnrc): Add blank line to separate sections

---

.github/workflows/test.yaml

Prefer the environment variable `$GITHUB_REPOSITORY` for the sake of reusability and succinctness.

ci(workflow): Don't hardcode repository name

---

.github/workflows/test.yaml

Prefer the environment variable `$GITHUB_API_URL` for the sake of succinctness.

ci(workflow): Don't hardcode GitHub API URL

---

.github/workflows/test.yaml

"Bearer" is recommended by the official GitHub documentation, because it works with JSON web tokens (JWT).

ci(workflow): Prefer "Bearer" to "token" for auth

---

.github/workflows/test.yaml

Single quotes prevent evaluation of Bash syntax, such as variable interpolation, so they are simpler and safer when variable interpolation is not desired.

ci(workflow): Prefer `'` to `"` for string literals

---

jest.config.ts

Setting `ts-jest` via `globals` is deprecated. Also, use the new, narrower `JestConfigWithTsJest` type introduced in ts-jest v29.

test(jest.config): Specify `ts-jest` via `transform`

---

.github/workflows/test.yaml

GitHub deprecated the `set-output` command, and recommends using the new environment files instead for security purposes.

ci(workflow): Port from `set-output` to env files

---

.mega-linter.yaml

Keep config keys that pertain to all tools in alphabetical order.

chore(MegaLinter): Sort non-tool-specific keys

---

.mega-linter.yaml

Preclude confusion regarding which logs were generated by which run.

ci(MegaLinter): Clear report before each run

---

.github/workflows/test.yaml

Replace `--fail` with `--fail-with-body` in cURL invocation that deletes test cache. This causes cURL to display any error message it may receive from the server, which is often helpful context to have when debugging.

ci(workflow): Print error messages from GitHub API

---

.github/workflows/test.yaml

The Restore Cache job fails when run from a forked repository, because forks have read-only permissions to GitHub APIs for security purposes. Suppress the failure in the failing step that deletes the test cache since the test cache is less than 2 KB in size. Make the test cache key unique to each workflow run attempt in order to continue testing cache saves after a run from a forked repository. This also eliminates a short race condition that previously could have resulted in false positives when the workflow was run concurrently with itself.

ci(workflow): Support running workflow from forks

---

.github/workflows/test.yaml

Unlike the run attempt count, the run ID is unique across workflow runs. In fact, unless a workflow is re-run, the run attempt count is always 1. Keep the run attempt count in the key to avoid collisions when the workflow is re-run.

ci(workflow): Add run ID to test cache key

---

.github/workflows/test.yaml

Only invalidate the Docker cache when the MegaLinter flavor or release change. Previously the cache was invalidated any time `.pre-commit-config.yaml` was modified. This made the cache less efficient since the pre-commit config is frequently modified.

ci(workflow): Make Docker cache key more precise

---

.mega-linter.yaml

Use the same pattern as the pre-commit exclude regex for consistency.

chore(MegaLinter): Simplify exclude regex

---

yarn.lock

A moderate severity security vulnerability was discovered in http-cache-semantics, a transitive Yarn dependency.

chore(http-cache-semantics): Bump v4.1.0 to v4.1.1

---

README.md

Resolves #97.
Replace `hashFiles(...)` with `hashFiles(paths)` to make it clear that `...` isn't a special symbol and that the user ought to pass one or more filepaths to `hashFiles`. Explicitly document that the user must select an appropriate key and cannot copy the example verbatim. Link to the specific section of the official GitHub cache action that documents how to create a cache key.

docs(README): Clarify how to create a cache key

---

.github/workflows/test.yaml

Implement partial cache restoration for Yarn, allowing cache hits when Yarn dependencies are upgraded. Yarn prevents partial cache restoration snowballing by removing no longer needed dependencies from the cache when `yarn install` is run.

ci(workflow): Partially restore Yarn cache

---

package.json
tsconfig.json
yarn.lock

We already upgraded from Node.js 16 to 18, so reflect that in our TypeScript configuration by upgrading from @tsconfig/node16-strictest-esm to @tsconfig/node18-strictest-esm.

chore(tsconfig): Upgrade from node16 to node18

---

jest.config.ts

`testEnvironment` began defaulting to `"node"` in Jest 27, and we are currently on Jest 29. `watchman` defaulted to `true` all long.

test(Jest): Remove `testEnvironment` and `watchman`

---

jest.config.ts

Jest only runs on the `*.ts` files in the `src` directory, so there have never been any `*.js` source files for ts-jest to transform. tsc and @vercel/ncc generate `*.js` output files in the `build` and `dist` directories, respectively, but ts-jest doesn't transform these.

test(jest.config): Stop transforming `*.js` files

---

.github/workflows/test.yaml

There was never anything generating a report at a path matching `reports/junit/*.xml`, so instructing EnricoMi/publish-unit-test-result-action to search for one there only served to slow it down.

ci(workflow): Stop publishing nonexistent report

---

.github/workflows/test.yaml
.gitignore
jest.config.ts

`coverageDirectory` is relative to `rootDir`, so Jest outputs test coverage reports to `src/reports/jest/` rather than `reports/jest/`. `outputDirectory` is not relative to `rootDir`, so include `rootDir` explicitly in the path so that unit tests are reported to the same directory as test coverage.

test(Jest): Update paths to reflect `rootDir` routes

---

.github/workflows/test.yaml

The `junit_files` argument to [EnricoMi/publish-unit-test-result-action](https://github.com/EnricoMi/publish-unit-test-result-action) was deprecated in favor of `files`.

ci(workflow): Replace `junit_files` with `files`

---

.gitattributes

Yarn generates `.pnp.loader.mjs` for ESM (ECMAScript modules) support. We already correctly configure Git to ignore whitespace errors in Yarn CJS (CommonJS) files, so do the same for `*.mjs` files.

ci(gitattributes): Ignore `*.mjs` whitespace errors

---

.github/workflows/test.yaml

Add minimal permissions to each job as needed rather than start broad and subtract.

ci(workflow): Set top-level permissions to `{}`

---

src/util.test.ts

TypeScript automatically infers the type of `""` to be `string`.

test(util): Remove unnecessary typing

---

.vscode/settings.json

VSCode search now excludes gitignored files by default.

chore(VSCode): Remove no longer needed exclude

---

src/docker.test.ts

TypeScript automatically infers argument types from default values.

test(docker): Remove unnecessary typing

---

src/main.test.ts
src/post.test.ts

Simplify `main.test.ts` and `post.test.ts` by moving the contents of their `beforeAll`s into their single tests. Use `jest.mocked()` to automatically convert the type of the imported docker modules to `jest.MockedObject<typeof import("./docker.js")>`.

test(action): Remove unnecessary `beforeAll`s

---

src/docker.test.ts
src/integration.test.ts
src/util.test.ts

Casting mocked modules to `any` prevents TypeScript from type checking. Jest offers `jest.mocked()` for the purpose of decorating the types of mocked objects with their Jest-imbued functions and properties. This allows TypeScript to enforce that the appropriate mock is assigned to the appropriate variable, for instance.

test(action): Prefer `jest.mocked()` to `<any>`

---

.github/workflows/test.yaml

When we added Windows support, the cache key for the delete step in our test workflow was not updated accordingly.

ci(workflow): Correct cache key for delete step

---

src/integration.test.ts

Prefer the shorthand notation for one-line functions in which the `return` statement and curly braces are omitted.

test(integration): Elide `return` in one-liners

---

.dictionary.txt
src/arbitraries/util.ts
src/integration.test.ts
src/util.test.ts
src/util.ts

Stdout and stderr frequently co-occur, so wrap them in a dedicated type. Create a corresponding fast-check arbitrary, `consoleOutput()`. Move our existing custom arbitrary, `platform()`, into the new dedicated arbitrary file, `src/arbitraries/util.ts`. Leverage `ConsoleOutput` in a new helper method, `joinOutput()`, to reduce duplication in the integration test.

style(util): Introduce `ConsoleOutput` type

---

src/integration.test.ts

The integration test doesn't mock any of our own production code since that is what it is testing. This error was asymptomatic since we didn't actually mock any of our production code, but now we stop giving the misleading impression that we might.

test(integration): Remove incorrect use of `jest.mocked()`

---

src/docker.test.ts
src/integration.test.ts
src/main.test.ts
src/post.test.ts
src/util.test.ts

Top-level `await` allows us to declare and initialize dynamic asynchronous imports at once using `const`. This empowers TypeScript to infer the appropriate types, eliminating the need to specify them explicitly.

test(action): Move `async` imports to top level

---

src/docker.test.ts
src/integration.test.ts
src/main.test.ts
src/post.test.ts
src/util.test.ts
types/aliases.ts

Prefer static type imports (using the `import` keyword) to dynamic type imports (using the `import()` function). Unlike regular static imports, static type imports do not interfere with mocking as they compile out, so there is no need to delay them until after our mocks are set up. Introduce `types/aliases.ts` to export convenient names for the shapes of our production modules that we import in our tests. We use these types to ensure that our mocks accurately reflect the shapes of their production counterparts.

test(action): Import types statically

---

.dictionary.txt

It was added to the software-terms dictionary upstream.

ci(dictionary): Remove "arbitraries" from custom dictionary

---

src/integration.test.ts

Explicitly type the return type of our mock of `cache.saveCache` and the `value` argument to our mock of `core.saveState`.

test(integration): Prefer explicit types to `any`

---

src/util.ts

Using the `any` type disables the type system, which typescript-eslint objects to, so switch to `unknown`, the only other option permitted by TypeScript.

style(util): Prefer `unknown` to `any` in catch

---

src/util.ts

Clarify and enforce that `ConsoleOutput` is a type rather than a value.

style(util): Prefer `export type` to `export`

---

.mega-linter.yaml

If a pre-command fails, fail MegaLinter, and display an error message rather than swallow the error.

ci(MegaLinter): Don't suppress pre-command errors

---

tsconfig.json

Include the `types` directory and Jest config in the TypeScript build to ensure that they compile.

ci(tsconfig): Include `types` directory and Jest config

---

src/util.ts

The two are often interchangeable, but prefer interfaces when either will do since they are defined statically rather than imperatively, making them slightly simpler.

style(util): Prefer `interface` to `type`

---

src/docker.test.ts

In Jest, mock names make poor keys for identifying mock instances since they are not guaranteed to be unique and default to `"jest.fn()"` unless explicitly specified. All of our mocks are hence currently named `"jest.fn()"`. The key collisions resulted in all call orders after the first being `undefined`, causing `assertCalledInOrder` to always succeed vacuously. Key mocks by reference instead so `assertCalledInOrder` asserts that mocks are called in the specified order as intended.

test(docker): Key mocks by reference, not name

---

src/docker.test.ts

Fail fast since the call order is `undefined` in this case, eliminating a dangerous cast from `number | undefined` to `number`.

test(docker): Check if mock called too few times

---

src/util.ts

Angle bracket casts can create confusion with generics.

style(util): Prefer `as` to angle brackets

---

src/integration.test.ts

Prefer the nullish coalescing operator, `??`, to the logical OR operator, `||`, because the former only coalesces on `null | undefined` rather than on any falsy value.

test(integration): Prefer `??` to `||`

---

src/integration.test.ts

For consistency, refer to the key parameter to the `cache.saveCache` mock by the same name used for the corresponding parameter to the `cache.restoreCache` mock.

test(integration): Rename `key` to `primaryKey`

---

src/integration.test.ts

Improve readability and the utility of stack traces by refraining from doing too much on a single line.

test(integration): Get key on its own line

---

src/docker.test.ts

The former has better performance than the spread operator for concatenating arrays.

test(docker): Prefer `concat` to `...`

---

src/docker.test.ts

`preexistingImages` and `newImages` are already guaranteed not to contain any duplicates either within or between them.

test(docker): Eliminate unnecessary deduplication

---

src/arbitraries/util.ts
src/docker.test.ts
src/integration.test.ts
src/util.test.ts

The `string` fast-check arbitrary only samples printable ASCII characters. Thus, it may overlook bugs that are only exposed by Unicode characters.

test(action): Prefer `fullUnicodeString` to `string`

---

src/arbitraries/util.ts
src/docker.test.ts

Introduce `uniquePair` arbitrary in `src/arbitraries/util.ts` that generates a 2-tuple of arrays with no overlap. Docker images can either be preexisting, that is present during the main step, or new, that is only present during the post step. Hence, restrict fast-check to cases without duplicates between preexisting and new Docker images. Previously, these duplicates were filtered out after the fact. Move this filtering into the arbitrary to produce more intuitive counterexamples. Modify the example that tested handling of duplicates accordingly.
Introduce `dockerImages` arbitrary in `src/arbitraries/util.ts` that forbids the empty string and newlines. Docker image names can neither be empty nor contain newlines, so there's no value in testing these cases that complicate test logic. …

test(docker): Refine Docker images arbitraries

---

yarn.lock

A moderate severity security vulnerability was recently discovered in semver, a transitive Yarn dependency.

fix(semver): Bump v7.5.1 to v7.5.4

---

package.json
yarn.lock

Prettier 3+ includes its own type definitions, so `@types/prettier` is no longer needed.

chore(@types/prettier): Remove no longer needed dependency

---

.mega-linter.yaml

MegaLinter recently fixed a number of bugs in the `EXTENDS` property in v6.14.0, v6.16.0, v6.18.0, v6.19.0, and v6.20.0. Leverage this improved support for config inheritance by extending a central MegaLinter configuration.

ci(MegaLinter): Reuse config from .github repo

---

.yarnrc.yml

The Yarn licenses plugin requires that all dependencies are installed.

docs(Yarn): Document need for `darwin` architecture

---

.vscode/settings.json

This setting is deprecated since the ESLint VSCode extension now detects the package manager automatically.

chore(VSCode): Remove `eslint.packageManager`

---

jest.config.ts

Jest began recommending use of this setting in TypeScript ESM projects when it was introduced in v27.

test(jest.config): Treat `*.ts` files as ESM

---

package.json

The `test` script runs tsc, then Jest. Decompose the `test` script for readability and to facilitate only running Jest via `yarn run jest:esm`.

test(Jest): Add `jest:esm` script

---

README.md
jest.config.ts
package.json
yarn.lock

Jest relies on ts-node to read its TypeScript config file directly. We already compile the file with tsc though, so eliminate the dependency, and read from the JavaScript config instead.

test(Jest): Eliminate dependency on ts-node

---

.pre-commit-config.yaml
.vscode/settings.json

The `yarn-sdks` hook was recently added to our pre-commit-hooks repository. Use it to ensure that our Yarn SDKs remain up-to-date.

ci(pre-commit): Add and run new `yarn-sdks` hook

---

package.json
yarn.lock

We are already using Node.js 20.9.0 via asdf, so use the corresponding version of `@types/node`.

chore(@types/node): Bump from v18.18.5 to v20.9.0

---

README.md

The file listing the pre-cached Docker images in the `ubuntu-22.04` GitHub-hosted runner was moved from the `images/linux` directory to the `images/ubuntu` directory within the `actions/runner-images` repository.

docs(README): Update broken `ubuntu-22.04` link

---

action.yaml

Closes #613.
We are already using Node.js 20.10.0 via asdf, so use the same major version of Node.js in the action.

fix(Node.js): Upgrade from node16 to node20

---

.dictionary.txt
.mega-linter.yaml
.trivyignore
.trivyignore.yaml

Use the more expressive YAML config format recently introduced in v0.45.0.

ci(Trivy): Port `.trivyignore` to `.trivyignore.yaml`
